site_name: opencell
theme: readthedocs
pages:
- Home: 'index.md'
- Functional overview: 'functional-overview/functional-overview.md'
- Technical overview: 'technical-overview/technical-overview.md'
- Quick start tutorials:
    - Marketing manager: 'quick-start-tutorials/quick-start-marketing-manager.md'
- User guide:
    - 'Marketing manager': 'marketing-manager/marketing-manager.md'
    - 'Customer care': 'customer-care/customer-care.md'
- Installation guide:
    - 'System requirements': 'installation-guide/system-requirements.md'
    - 'Install using Docker': 'installation-guide/deploy-docker.md'
    - 'Install from scratch' : 'installation-guide/deploy-from-scratch.md'